apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  #minReadySeconds: 10
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template: # pod template
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---

apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
    - name: queue-container
      image: richardchesterwood/k8s-fleetman-queue:release1