apiVersion: v1
kind: Pod
metadata:
  name: webapp-metadata
  labels:
    app: my-webapp
spec:
  containers:
    - name: webapp-container
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0
